name: my_extensions
version: 1.0.0
description: A rich set of extension methods for Dart and Flutter (Strings, numbers, lists, maps, dates, context, bool).
homepage: https://example.com
repository: https://example.com/repository
issue_tracker: https://example.com/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
topics:
  - extensions
  - utils
  - dart
  - flutter
